// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OkeanChat.Data;

#nullable disable

namespace OkeanChat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022052405_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OkeanChat.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 22, 5, 24, 4, 416, DateTimeKind.Utc).AddTicks(5901),
                            Description = "General discussion channel",
                            IsActive = true,
                            Name = "general"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 22, 5, 24, 4, 416, DateTimeKind.Utc).AddTicks(5906),
                            Description = "Random chat and off-topic discussions",
                            IsActive = true,
                            Name = "random"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 22, 5, 24, 4, 416, DateTimeKind.Utc).AddTicks(5907),
                            Description = "Important announcements",
                            IsActive = true,
                            Name = "announcements"
                        });
                });

            modelBuilder.Entity("OkeanChat.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelId = 1,
                            Content = "Welcome to OkeanChat! 🚀",
                            CreatedAt = new DateTime(2025, 10, 22, 4, 54, 4, 416, DateTimeKind.Utc).AddTicks(6034),
                            IsEdited = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChannelId = 1,
                            Content = "Hello everyone! 👋",
                            CreatedAt = new DateTime(2025, 10, 22, 4, 59, 4, 416, DateTimeKind.Utc).AddTicks(6038),
                            IsEdited = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ChannelId = 2,
                            Content = "This is a test message in random channel",
                            CreatedAt = new DateTime(2025, 10, 22, 5, 4, 4, 416, DateTimeKind.Utc).AddTicks(6040),
                            IsEdited = false,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("OkeanChat.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://via.placeholder.com/40/7289da/ffffff?text=A",
                            CreatedAt = new DateTime(2025, 10, 22, 5, 24, 4, 416, DateTimeKind.Utc).AddTicks(6013),
                            Email = "admin@okeanchat.com",
                            LastSeen = new DateTime(2025, 10, 22, 5, 24, 4, 416, DateTimeKind.Utc).AddTicks(6013),
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://via.placeholder.com/40/43b581/ffffff?text=T",
                            CreatedAt = new DateTime(2025, 10, 22, 5, 24, 4, 416, DateTimeKind.Utc).AddTicks(6016),
                            Email = "test@okeanchat.com",
                            LastSeen = new DateTime(2025, 10, 22, 5, 24, 4, 416, DateTimeKind.Utc).AddTicks(6017),
                            Username = "TestUser"
                        });
                });

            modelBuilder.Entity("OkeanChat.Models.Message", b =>
                {
                    b.HasOne("OkeanChat.Models.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OkeanChat.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OkeanChat.Models.Channel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OkeanChat.Models.User", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
